[tool.poetry]
name = "discord-bot"
version = "0.1.0"
description = ""
authors = ["ngmtine <ngmfries@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
discord-py = "^2.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
